### PR TITLE
Fixed git checksum

### PR DESCRIPTION
**Pull request by brianhob27**
# Description

Fixed windows git checksum from https://github.com/git-for-windows/git/releases/tag/v2.35.1.windows.1
Obvious fix.

## Check List

- [x] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by bmhughes** [comment]
Thanks for the PR!

If you could update the rspec tests so they pass and add a CHANGELOG entry then we can get this released 🚀

**Comment by brianhob27** [comment]
Hi @bmhughes I have made the change, let me know if there's anything else 😄

**Review by bmhughes — APPROVED** [review]

**Comment by bmhughes** [comment]
> Hi @bmhughes I have made the change, let me know if there's anything else 😄

Looks great, thanks!

**Comment by kitchen-porter** [comment]
Released as: [11.1.1](https://github.com/sous-chefs/git/releases/tag/11.1.1)

**Pull request merged**
