### PR TITLE
Automated PR: Standardising Files

### PR DESCRIPTION
**Pull request by kitchen-porter**
This PR will standardise the files we have with out agreed spec in sous-chefs/repo-management.
This repo has been identified by topic(s) of chef-cookbook

### CODE REVIEW

**Comment by damacus** [comment]
I think this bubbles up #150

**Comment by ramereth** [comment]
@damacus yeah, this is fun to test in Github Actions since it already comes with Git installed. I forgot to go back to this and see if I could get it fixed properly. I'm not entirely sure what else we need to do to get it to work.

**Comment by damacus** [comment]
I think we probably just need to set the override option when we're on MacOS and that should probably fix it.

**Comment by kitchen-porter** [comment]
Released as: [11.1.0](https://github.com/sous-chefs/git/releases/tag/11.1.0)

**Pull request merged**
