### PR TITLE
Updated git version and checksums for chef-17 testing

### PR DESCRIPTION
**Pull request by johnmccrae**
# Description

Updating versions and checksums for Chef testing

## Issues Resolved

List any existing issues this PR resolves

## Check List

- [ ] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by Stromweld** [comment]
@johnmccrae can you add an item under ##unreleased for the change you made.

**Review by Stromweld — APPROVED** [review]
LGTM

**Comment by Stromweld** [comment]
Failed test is unrelated to this change.

**Comment by kitchen-porter** [comment]
Released as: [11.2.0](https://github.com/sous-chefs/git/releases/tag/11.2.0)

**Pull request merged**
