### PR TITLE
Enable unified_mode for Chef 17 compatibility

### PR DESCRIPTION
**Pull request by detjensrobert**
# Description

- Enable `unified_mode` for Chef 17 compatibility
- Add some missing test coverage
- Convert `git_service` LWRP to custom resource
- Convert `git_client` LWRP to custom resource
- Use ark for `git_client` source install instead of manual commands

## Check List

- [x] All tests pass. See TESTING.md for details.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by detjensrobert** [comment]
Since this is a major version bump, should I also convert the `git_client` LWRP to custom resources using `provides:`? The source install provider would need to be changed to an action, e.g. `:install_from_source` instead of a separate linux provider.

**Comment by ramereth** [comment]
> Since this is a major version bump, should I also convert the `git_client` LWRP to custom resources using `provides:`? The source install provider would need to be changed to an action, e.g. `:install_from_source` instead of a separate linux provider.

Yes please.

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This is a big Pull Request.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by damacus — APPROVED** [review]
Happy with it working as is. Can we get the MacOS tests fixed in a future PR?

**Comment by detjensrobert** [comment]
> Can we get the MacOS tests fixed in a future PR?

Yep, I can do that :+1:

**Comment by kitchen-porter** [comment]
Released as: [11.0.0](https://github.com/sous-chefs/git/releases/tag/11.0.0)

**Pull request merged**
